server:
  port: 9009
  
spring:
  application:
    name: UMS-BI-REPORTING-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    password: manager
    url: jdbc:postgresql://localhost:5432/umsbireportdb
    #url: jdbc:postgresql://10.10.1.224:5432/users
    username: postgres
  devtools:
    restart:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  #zipkin:
    #base-url: http://127.0.0.1:9411/    
 